server:
  port: 8761
spring:
  application:
    name: eureka-server-one
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
